"""empty message

Revision ID: 039607e93ff7
Revises: 7f73f9c4915c
Create Date: 2023-11-03 03:24:51.789889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '039607e93ff7'
down_revision = '7f73f9c4915c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_visits',
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=20), nullable=False),
    sa.Column('date_of_visit', sa.Date(), nullable=False),
    sa.Column('nature_of_concern', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student_information.student_id'], ),
    sa.PrimaryKeyConstraint('visit_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_visits')
    # ### end Alembic commands ###
