"""empty message

Revision ID: 0cceb81b284b
Revises: e4495e8c8910
Create Date: 2023-10-31 05:11:06.597943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cceb81b284b'
down_revision = 'e4495e8c8910'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('family_background', schema=None) as batch_op:
        batch_op.add_column(sa.Column('father_last_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('mother_last_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('father_first_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('mother_first_name', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('family_background', schema=None) as batch_op:
        batch_op.drop_column('mother_first_name')
        batch_op.drop_column('father_first_name')
        batch_op.drop_column('mother_last_name')
        batch_op.drop_column('father_last_name')

    # ### end Alembic commands ###
