"""empty message

Revision ID: 0e73e5ba2f7c
Revises: 169141ed3186
Create Date: 2024-03-02 15:03:56.631693

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0e73e5ba2f7c'
down_revision = '169141ed3186'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('siblings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('rel_qual', sa.String(length=50), nullable=True),
    sa.Column('family_background_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['family_background_id'], ['family_background.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('family_background', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_location', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('raised_by', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('rel_qual_mother', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('rel_qual_father', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('rel_qual_step_parent', sa.String(length=50), nullable=True))
        batch_op.drop_column('mother_last_name')
        batch_op.drop_column('mother_age')
        batch_op.drop_column('mother_first_name')
        batch_op.drop_column('father_first_name')
        batch_op.drop_column('father_age')
        batch_op.drop_column('father_last_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('family_background', schema=None) as batch_op:
        batch_op.add_column(sa.Column('father_last_name', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('father_age', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('father_first_name', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('mother_first_name', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('mother_age', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('mother_last_name', mysql.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('rel_qual_step_parent')
        batch_op.drop_column('rel_qual_father')
        batch_op.drop_column('rel_qual_mother')
        batch_op.drop_column('raised_by')
        batch_op.drop_column('birth_location')

    op.drop_table('siblings')
    # ### end Alembic commands ###
