"""empty message

Revision ID: 169141ed3186
Revises: 755a9b3f4cf7
Create Date: 2024-03-02 14:33:13.094284

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '169141ed3186'
down_revision = '755a9b3f4cf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('basic_information', schema=None) as batch_op:
        batch_op.add_column(sa.Column('residence', sa.String(length=100), nullable=True))
        batch_op.drop_column('home_address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('basic_information', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_address', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('residence')

    # ### end Alembic commands ###
