"""empty message

Revision ID: 1f1be2a282fa
Revises: 5d537b6b8661
Create Date: 2024-02-27 14:18:55.586797

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1f1be2a282fa'
down_revision = '5d537b6b8661'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('otp_secret')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_secret', mysql.VARCHAR(length=6), nullable=True))

    # ### end Alembic commands ###
