"""empty message

Revision ID: 2c09718fe5f3
Revises: 0e73e5ba2f7c
Create Date: 2024-03-02 15:25:56.951885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c09718fe5f3'
down_revision = '0e73e5ba2f7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('legal_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conviction', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('conviction_outcome', sa.String(length=50), nullable=True))

    with op.batch_alter_table('occupational_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employment_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('satisfaction', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('satisfaction_reason', sa.String(length=200), nullable=True))

    with op.batch_alter_table('substance_abuse_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('treatment_program_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('treatment_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('treatment_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('treatment_outcome', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('substance_abuse_history', schema=None) as batch_op:
        batch_op.drop_column('treatment_outcome')
        batch_op.drop_column('treatment_date')
        batch_op.drop_column('treatment_type')
        batch_op.drop_column('treatment_program_name')

    with op.batch_alter_table('occupational_history', schema=None) as batch_op:
        batch_op.drop_column('satisfaction_reason')
        batch_op.drop_column('satisfaction')
        batch_op.drop_column('employment_status')

    with op.batch_alter_table('legal_history', schema=None) as batch_op:
        batch_op.drop_column('conviction_outcome')
        batch_op.drop_column('conviction')

    # ### end Alembic commands ###
