"""empty message

Revision ID: 2fd808d5ce19
Revises: ac7df021008b
Create Date: 2024-02-05 20:45:13.910886

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2fd808d5ce19'
down_revision = 'ac7df021008b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_information', schema=None) as batch_op:
        batch_op.alter_column('physician_name',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_information', schema=None) as batch_op:
        batch_op.alter_column('physician_name',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###
