"""empty message

Revision ID: 494383cf7e09
Revises: e58b79cd1826
Create Date: 2023-10-31 00:28:22.947346

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '494383cf7e09'
down_revision = 'e58b79cd1826'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_information', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campus', sa.String(length=20), nullable=False))
        batch_op.alter_column('course',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_information', schema=None) as batch_op:
        batch_op.alter_column('course',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('campus')

    # ### end Alembic commands ###
