"""empty message

Revision ID: 829a17f5c1db
Revises: c7ba76ab2c7a
Create Date: 2023-10-31 05:05:20.648586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '829a17f5c1db'
down_revision = 'c7ba76ab2c7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_information', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'courses', ['course_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_information', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('course_id')

    # ### end Alembic commands ###
