"""empty message

Revision ID: 8814988415fe
Revises: aa4d8c404f7a
Create Date: 2024-03-02 16:10:30.591416

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8814988415fe'
down_revision = 'aa4d8c404f7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('substance_abuse_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('benzo_age_first_use', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('benzo_frequency_of_use', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('benzo_amount_used', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('benzo__way_of_intake', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('hallucinogens_age_first_use', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('hallucinogens_frequency_of_use', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('hallucinogens_amount_used', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('hallucinogens_way_of_intake', sa.String(length=50), nullable=True))
        batch_op.drop_column('benzo_meds_amount_used')
        batch_op.drop_column('hallucinogens_meds_amount_used')
        batch_op.drop_column('hallucinogens_meds_age_first_use')
        batch_op.drop_column('benzo_meds_way_of_intake')
        batch_op.drop_column('hallucinogens_meds_way_of_intake')
        batch_op.drop_column('benzo_meds_age_first_use')
        batch_op.drop_column('hallucinogens_meds_frequency_of_use')
        batch_op.drop_column('benzo_meds_frequency_of_use')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('substance_abuse_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('benzo_meds_frequency_of_use', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('hallucinogens_meds_frequency_of_use', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('benzo_meds_age_first_use', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('hallucinogens_meds_way_of_intake', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('benzo_meds_way_of_intake', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('hallucinogens_meds_age_first_use', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('hallucinogens_meds_amount_used', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('benzo_meds_amount_used', mysql.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('hallucinogens_way_of_intake')
        batch_op.drop_column('hallucinogens_amount_used')
        batch_op.drop_column('hallucinogens_frequency_of_use')
        batch_op.drop_column('hallucinogens_age_first_use')
        batch_op.drop_column('benzo__way_of_intake')
        batch_op.drop_column('benzo_amount_used')
        batch_op.drop_column('benzo_frequency_of_use')
        batch_op.drop_column('benzo_age_first_use')

    # ### end Alembic commands ###
