"""empty message

Revision ID: 8d5151085dc0
Revises: 
Create Date: 2024-03-02 17:03:30.419419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d5151085dc0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('basic_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=20), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('course', sa.String(length=100), nullable=False),
    sa.Column('year_level', sa.String(length=20), nullable=True),
    sa.Column('campus', sa.String(length=20), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('civil_status', sa.String(length=20), nullable=True),
    sa.Column('nationality', sa.String(length=50), nullable=True),
    sa.Column('religion', sa.String(length=50), nullable=True),
    sa.Column('residence', sa.String(length=100), nullable=True),
    sa.Column('contact_number', sa.String(length=20), nullable=True),
    sa.Column('email_address', sa.String(length=120), nullable=False),
    sa.Column('guardian_name', sa.String(length=50), nullable=True),
    sa.Column('guardian_address', sa.String(length=50), nullable=True),
    sa.Column('guardian_contact', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_table('colleges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('additional_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('to_work_on', sa.String(length=500), nullable=True),
    sa.Column('expectations', sa.String(length=500), nullable=True),
    sa.Column('things_to_change', sa.String(length=500), nullable=True),
    sa.Column('other_information', sa.String(length=500), nullable=True),
    sa.Column('student_id', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['basic_information.student_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('educational_background',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['basic_information.student_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('family_background',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('birth_location', sa.String(length=50), nullable=True),
    sa.Column('raised_by', sa.String(length=50), nullable=True),
    sa.Column('rel_qual_mother', sa.String(length=50), nullable=True),
    sa.Column('rel_qual_father', sa.String(length=50), nullable=True),
    sa.Column('rel_qual_step_parent', sa.String(length=50), nullable=True),
    sa.Column('family_abuse_history', sa.String(length=300), nullable=True),
    sa.Column('family_mental_history', sa.String(length=300), nullable=True),
    sa.Column('additional_information', sa.String(length=300), nullable=True),
    sa.Column('student_id', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['basic_information.student_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('health_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medication_and_dose', sa.String(length=100), nullable=True),
    sa.Column('serious_ch_illnesses_history', sa.String(length=100), nullable=True),
    sa.Column('head_injuries', sa.Boolean(), nullable=True),
    sa.Column('lose_consciousness', sa.Boolean(), nullable=True),
    sa.Column('convulsions_or_seizures', sa.Boolean(), nullable=True),
    sa.Column('fever', sa.Boolean(), nullable=True),
    sa.Column('allergies', sa.String(length=100), nullable=True),
    sa.Column('current_physical_health', sa.String(length=20), nullable=True),
    sa.Column('last_check_up', sa.Date(), nullable=True),
    sa.Column('has_physician', sa.Boolean(), nullable=True),
    sa.Column('physician_name', sa.String(length=50), nullable=True),
    sa.Column('physician_email', sa.String(length=50), nullable=True),
    sa.Column('physician_number', sa.String(length=20), nullable=True),
    sa.Column('student_id', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['basic_information.student_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('history_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('information_provider', sa.String(length=50), nullable=True),
    sa.Column('current_problem', sa.String(length=200), nullable=True),
    sa.Column('problem_length', sa.String(length=200), nullable=True),
    sa.Column('stressors', sa.String(length=200), nullable=True),
    sa.Column('substance_abuse', sa.Boolean(), nullable=True),
    sa.Column('addiction', sa.Boolean(), nullable=True),
    sa.Column('depression_sad_down_feelings', sa.Boolean(), nullable=True),
    sa.Column('high_low_energy_level', sa.Boolean(), nullable=True),
    sa.Column('angry_irritable', sa.Boolean(), nullable=True),
    sa.Column('loss_of_interest', sa.Boolean(), nullable=True),
    sa.Column('difficulty_enjoying_things', sa.Boolean(), nullable=True),
    sa.Column('crying_spells', sa.Boolean(), nullable=True),
    sa.Column('decreased_motivation', sa.Boolean(), nullable=True),
    sa.Column('withdrawing_from_people', sa.Boolean(), nullable=True),
    sa.Column('mood_swings', sa.Boolean(), nullable=True),
    sa.Column('black_and_white_thinking', sa.Boolean(), nullable=True),
    sa.Column('negative_thinking', sa.Boolean(), nullable=True),
    sa.Column('change_in_weight_or_appetite', sa.Boolean(), nullable=True),
    sa.Column('change_in_sleeping_pattern', sa.Boolean(), nullable=True),
    sa.Column('suicidal_thoughts_or_plans', sa.Boolean(), nullable=True),
    sa.Column('self_harm', sa.Boolean(), nullable=True),
    sa.Column('homicidal_thoughts_or_plans', sa.Boolean(), nullable=True),
    sa.Column('difficulty_focusing', sa.Boolean(), nullable=True),
    sa.Column('feelings_of_hopelessness', sa.Boolean(), nullable=True),
    sa.Column('feelings_of_shame_or_guilt', sa.Boolean(), nullable=True),
    sa.Column('feelings_of_inadequacy', sa.Boolean(), nullable=True),
    sa.Column('low_self_esteem', sa.Boolean(), nullable=True),
    sa.Column('anxious_nervous_tense_feelings', sa.Boolean(), nullable=True),
    sa.Column('panic_attacks', sa.Boolean(), nullable=True),
    sa.Column('racing_or_scrambled_thoughts', sa.Boolean(), nullable=True),
    sa.Column('bad_or_unwanted_thoughts', sa.Boolean(), nullable=True),
    sa.Column('flashbacks_or_nightmares', sa.Boolean(), nullable=True),
    sa.Column('muscle_tensions_aches', sa.Boolean(), nullable=True),
    sa.Column('hearing_voices_or_seeing_things', sa.Boolean(), nullable=True),
    sa.Column('thoughts_of_running_away', sa.Boolean(), nullable=True),
    sa.Column('paranoid_thoughts', sa.Boolean(), nullable=True),
    sa.Column('feelings_of_frustration', sa.Boolean(), nullable=True),
    sa.Column('feelings_of_being_cheated', sa.Boolean(), nullable=True),
    sa.Column('perfectionism', sa.Boolean(), nullable=True),
    sa.Column('counting_washing_checking', sa.Boolean(), nullable=True),
    sa.Column('distorted_body_image', sa.Boolean(), nullable=True),
    sa.Column('concerns_about_dieting', sa.Boolean(), nullable=True),
    sa.Column('loss_of_control_over_eating', sa.Boolean(), nullable=True),
    sa.Column('binge_eating_or_purging', sa.Boolean(), nullable=True),
    sa.Column('rules_about_eating', sa.Boolean(), nullable=True),
    sa.Column('compensating_for_eating', sa.Boolean(), nullable=True),
    sa.Column('excessive_exercise', sa.Boolean(), nullable=True),
    sa.Column('indecisiveness_about_career', sa.Boolean(), nullable=True),
    sa.Column('job_problems', sa.Boolean(), nullable=True),
    sa.Column('other', sa.String(length=100), nullable=True),
    sa.Column('previous_treatments', sa.Boolean(), nullable=True),
    sa.Column('previous_treatments_likes_dislikes', sa.String(length=400), nullable=True),
    sa.Column('previous_treatments_learned', sa.String(length=400), nullable=True),
    sa.Column('previous_treatments_like_to_continue', sa.String(length=400), nullable=True),
    sa.Column('previous_hospital_stays_psych', sa.Boolean(), nullable=True),
    sa.Column('current_thoughts_to_harm', sa.Boolean(), nullable=True),
    sa.Column('past_thoughts_to_harm', sa.Boolean(), nullable=True),
    sa.Column('student_id', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['basic_information.student_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('legal_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pending_criminal_charges', sa.Boolean(), nullable=True),
    sa.Column('on_probation', sa.Boolean(), nullable=True),
    sa.Column('has_been_arrested', sa.Boolean(), nullable=True),
    sa.Column('conviction', sa.String(length=50), nullable=True),
    sa.Column('conviction_outcome', sa.String(length=50), nullable=True),
    sa.Column('student_id', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['basic_information.student_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('occupational_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employment_status', sa.String(length=20), nullable=True),
    sa.Column('satisfaction', sa.String(length=20), nullable=True),
    sa.Column('satisfaction_reason', sa.String(length=200), nullable=True),
    sa.Column('student_id', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['basic_information.student_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('social_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relationship_with_peers', sa.String(length=300), nullable=True),
    sa.Column('social_support_network', sa.String(length=300), nullable=True),
    sa.Column('hobbies_or_interests', sa.String(length=300), nullable=True),
    sa.Column('cultural_concerns', sa.String(length=300), nullable=True),
    sa.Column('student_id', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['basic_information.student_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_visits',
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('date_of_visit', sa.Date(), nullable=False),
    sa.Column('nature_of_concern', sa.String(length=100), nullable=True),
    sa.Column('student_id', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['basic_information.student_id'], ),
    sa.PrimaryKeyConstraint('visit_id')
    )
    op.create_table('substance_abuse_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('struggled_with_substance_abuse', sa.Boolean(), nullable=True),
    sa.Column('alcohol', sa.Boolean(), nullable=True),
    sa.Column('alcohol_age_first_use', sa.String(length=50), nullable=True),
    sa.Column('alcohol_frequency_of_use', sa.String(length=50), nullable=True),
    sa.Column('alcohol_amount_used', sa.String(length=50), nullable=True),
    sa.Column('alcohol_way_of_intake', sa.String(length=50), nullable=True),
    sa.Column('cigarette', sa.Boolean(), nullable=True),
    sa.Column('cigarette_age_first_use', sa.String(length=50), nullable=True),
    sa.Column('cigarette_frequency_of_use', sa.String(length=50), nullable=True),
    sa.Column('cigarette_amount_used', sa.String(length=50), nullable=True),
    sa.Column('cigarette_way_of_intake', sa.String(length=50), nullable=True),
    sa.Column('marijuana', sa.Boolean(), nullable=True),
    sa.Column('marijuana_age_first_use', sa.String(length=50), nullable=True),
    sa.Column('marijuana_frequency_of_use', sa.String(length=50), nullable=True),
    sa.Column('marijuana_amount_used', sa.String(length=50), nullable=True),
    sa.Column('marijuana_way_of_intake', sa.String(length=50), nullable=True),
    sa.Column('cocaine', sa.Boolean(), nullable=True),
    sa.Column('cocaine_age_first_use', sa.String(length=50), nullable=True),
    sa.Column('cocaine_frequency_of_use', sa.String(length=50), nullable=True),
    sa.Column('cocaine_amount_used', sa.String(length=50), nullable=True),
    sa.Column('cocaine_way_of_intake', sa.String(length=50), nullable=True),
    sa.Column('heroin', sa.Boolean(), nullable=True),
    sa.Column('heroin_age_first_use', sa.String(length=50), nullable=True),
    sa.Column('heroin_frequency_of_use', sa.String(length=50), nullable=True),
    sa.Column('heroin_amount_used', sa.String(length=50), nullable=True),
    sa.Column('heroin_way_of_intake', sa.String(length=50), nullable=True),
    sa.Column('amphetamines', sa.Boolean(), nullable=True),
    sa.Column('amphetamines_age_first_use', sa.String(length=50), nullable=True),
    sa.Column('amphetamines_frequency_of_use', sa.String(length=50), nullable=True),
    sa.Column('amphetamines_amount_used', sa.String(length=50), nullable=True),
    sa.Column('amphetamines_way_of_intake', sa.String(length=50), nullable=True),
    sa.Column('club_drugs', sa.Boolean(), nullable=True),
    sa.Column('club_drugs_age_first_use', sa.String(length=50), nullable=True),
    sa.Column('club_drugs_frequency_of_use', sa.String(length=50), nullable=True),
    sa.Column('club_drugs_amount_used', sa.String(length=50), nullable=True),
    sa.Column('club_drugs_way_of_intake', sa.String(length=50), nullable=True),
    sa.Column('pain_meds', sa.Boolean(), nullable=True),
    sa.Column('pain_meds_age_first_use', sa.String(length=50), nullable=True),
    sa.Column('pain_meds_frequency_of_use', sa.String(length=50), nullable=True),
    sa.Column('pain_meds_amount_used', sa.String(length=50), nullable=True),
    sa.Column('pain_meds_way_of_intake', sa.String(length=50), nullable=True),
    sa.Column('benzo', sa.Boolean(), nullable=True),
    sa.Column('benzo_age_first_use', sa.String(length=50), nullable=True),
    sa.Column('benzo_frequency_of_use', sa.String(length=50), nullable=True),
    sa.Column('benzo_amount_used', sa.String(length=50), nullable=True),
    sa.Column('benzo_way_of_intake', sa.String(length=50), nullable=True),
    sa.Column('hallucinogens', sa.Boolean(), nullable=True),
    sa.Column('hallucinogens_age_first_use', sa.String(length=50), nullable=True),
    sa.Column('hallucinogens_frequency_of_use', sa.String(length=50), nullable=True),
    sa.Column('hallucinogens_amount_used', sa.String(length=50), nullable=True),
    sa.Column('hallucinogens_way_of_intake', sa.String(length=50), nullable=True),
    sa.Column('other_meds', sa.Boolean(), nullable=True),
    sa.Column('other_meds_age_first_use', sa.String(length=50), nullable=True),
    sa.Column('other_meds_frequency_of_use', sa.String(length=50), nullable=True),
    sa.Column('other_meds_amount_used', sa.String(length=50), nullable=True),
    sa.Column('other_meds_way_of_intake', sa.String(length=50), nullable=True),
    sa.Column('treatment_program_name', sa.String(length=50), nullable=False),
    sa.Column('treatment_type', sa.String(length=50), nullable=False),
    sa.Column('treatment_date', sa.Date(), nullable=True),
    sa.Column('treatment_outcome', sa.String(length=100), nullable=True),
    sa.Column('student_id', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['basic_information.student_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('siblings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('rel_qual', sa.String(length=50), nullable=True),
    sa.Column('family_background_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['family_background_id'], ['family_background.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('siblings')
    op.drop_table('substance_abuse_history')
    op.drop_table('student_visits')
    op.drop_table('social_history')
    op.drop_table('occupational_history')
    op.drop_table('legal_history')
    op.drop_table('history_information')
    op.drop_table('health_information')
    op.drop_table('family_background')
    op.drop_table('educational_background')
    op.drop_table('courses')
    op.drop_table('additional_information')
    op.drop_table('users')
    op.drop_table('colleges')
    op.drop_table('basic_information')
    # ### end Alembic commands ###
