"""empty message

Revision ID: 966f2c087187
Revises: 
Create Date: 2023-10-31 05:58:04.049607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '966f2c087187'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('college', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=20), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('course', sa.String(length=100), nullable=False),
    sa.Column('year_level', sa.String(length=20), nullable=True),
    sa.Column('gpa', sa.Float(), nullable=True),
    sa.Column('campus', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('educational_background',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('senior_high_school', sa.String(length=100), nullable=True),
    sa.Column('shs_strand', sa.String(length=100), nullable=True),
    sa.Column('shs_graduation_year', sa.Integer(), nullable=True),
    sa.Column('junior_high_school', sa.String(length=100), nullable=True),
    sa.Column('jhs_graduation_year', sa.Integer(), nullable=True),
    sa.Column('elementary_school', sa.String(length=100), nullable=True),
    sa.Column('elementary_graduation_year', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student_information.student_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('family_background',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('father_age', sa.Integer(), nullable=True),
    sa.Column('mother_age', sa.Integer(), nullable=True),
    sa.Column('father_last_name', sa.String(length=50), nullable=True),
    sa.Column('mother_last_name', sa.String(length=50), nullable=True),
    sa.Column('father_first_name', sa.String(length=50), nullable=True),
    sa.Column('mother_first_name', sa.String(length=50), nullable=True),
    sa.Column('student_id', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student_information.student_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('health_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('sight', sa.String(length=20), nullable=True),
    sa.Column('hearing', sa.String(length=20), nullable=True),
    sa.Column('speech', sa.String(length=20), nullable=True),
    sa.Column('general_health', sa.String(length=100), nullable=True),
    sa.Column('experienced_sickness', sa.String(length=3), nullable=True),
    sa.Column('student_id', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student_information.student_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personal_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('contact_number', sa.String(length=20), nullable=True),
    sa.Column('religion', sa.String(length=50), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('place_of_birth', sa.String(length=100), nullable=True),
    sa.Column('nationality', sa.String(length=50), nullable=True),
    sa.Column('counseling_history', sa.String(length=100), nullable=True),
    sa.Column('residence', sa.String(length=100), nullable=True),
    sa.Column('student_id', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student_information.student_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('psychological_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('learning_styles', sa.String(length=100), nullable=True),
    sa.Column('personality_test', sa.String(length=100), nullable=True),
    sa.Column('iq_test', sa.String(length=100), nullable=True),
    sa.Column('student_id', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student_information.student_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('psychological_assessments')
    op.drop_table('personal_information')
    op.drop_table('health_information')
    op.drop_table('family_background')
    op.drop_table('educational_background')
    op.drop_table('users')
    op.drop_table('student_information')
    op.drop_table('courses')
    # ### end Alembic commands ###
