"""empty message

Revision ID: aa4d8c404f7a
Revises: 2c09718fe5f3
Create Date: 2024-03-02 16:05:45.892483

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aa4d8c404f7a'
down_revision = '2c09718fe5f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('substance_abuse_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('other_meds', sa.Boolean(), nullable=True))
        batch_op.drop_column('other')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('substance_abuse_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('other', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_column('other_meds')

    # ### end Alembic commands ###
