"""empty message

Revision ID: ac7df021008b
Revises: 68d1a7b1e07c
Create Date: 2024-02-05 20:44:44.907733

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ac7df021008b'
down_revision = '68d1a7b1e07c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history_information', schema=None) as batch_op:
        batch_op.alter_column('information_provider',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history_information', schema=None) as batch_op:
        batch_op.alter_column('information_provider',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###
