"""empty message

Revision ID: e4495e8c8910
Revises: 829a17f5c1db
Create Date: 2023-10-31 05:07:59.336118

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e4495e8c8910'
down_revision = '829a17f5c1db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('family_background', schema=None) as batch_op:
        batch_op.drop_column('mother_last_name')
        batch_op.drop_column('mother_first_name')
        batch_op.drop_column('father_last_name')
        batch_op.drop_column('father_first_name')

    with op.batch_alter_table('student_information', schema=None) as batch_op:
        batch_op.drop_constraint('student_information_ibfk_1', type_='foreignkey')
        batch_op.drop_column('course_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_information', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('student_information_ibfk_1', 'courses', ['course_id'], ['id'])

    with op.batch_alter_table('family_background', schema=None) as batch_op:
        batch_op.add_column(sa.Column('father_first_name', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('father_last_name', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('mother_first_name', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('mother_last_name', mysql.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
