"""empty message

Revision ID: f35797c538c5
Revises: 966f2c087187
Create Date: 2023-10-31 06:08:00.723077

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f35797c538c5'
down_revision = '966f2c087187'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colleges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('college_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'colleges', ['college_id'], ['id'])
        batch_op.drop_column('college')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('college', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('college_id')

    op.drop_table('colleges')
    # ### end Alembic commands ###
